name: Build Docker

on: workflow_dispatch
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PW }}
    - name: Building docker
      run: docker image build . -t "${{ secrets.DOCKER_HUB_USERNAME }}"/main:example-aio

    - name: Pushing docker to docker.io
      run: docker push "${{ secrets.DOCKER_HUB_USERNAME }}"/main:example-aio
